### ISSUE TITLE
Question: Why do reference types in models invalidate table creation?

### ISSUE THREAD

**Issue by ACReeser** [zzzprojects/nmemory#12]
I intended to use NMemory as an alternate backend for testing.  I set up the mapping for a few tables, and then found (via runtime `ArgumentException`) that table creation fails for entities that have reference properties (specifically, collections). My intent was to use nmemory for everything but the collections defined on the model, and have a repository class load the collections. My expectations were that NMemory would allow the table to be created and ignore the collection properties. This is fairly normal in other ORM libraries like Linq2Sql or EF.

Digging into the source, I see this check is handled in the constructor of `Table<TEntity, TPrimaryKey>`, the abstract class for `BasicTable`s. 

Is there a technical reason for disallowing reference type properties? Can these properties just be ignored instead of throwing an exception? 

If I were using NMemory for a toy project I would find a way for the models to not have their collection properties defined at the model level, but because I'm using this in a larger project and just for mock data, I am hesitant to change the models because the mocking framework dictates it.

If this issue is not tractable, would a pull request to add documentation for this validation be acceptable?

**Comment by tamasflamich** [comment]
Hi @ACReeser - Probably this is a late response, but reference types are [disabled](https://github.com/tamasflamich/nmemory/blob/master/Main/Source/NMemory/Tables/Table%602.cs#L742) in order to prevent unexpected behaviors as they would allow users to modify the stored data without interacting with the database engine. 

However, you are free to override this behavior or simply wrap your reference type with a `struct`.
