### ISSUE TITLE
Method 'CreateTable' in type does not have an implementation

### ISSUE THREAD

**Issue by jsgoupil** [zzzprojects/nmemory#32]
With 2.0.7 I get the following error:

```
Message: System.TypeInitializationException : The type initializer for 'Effort.Internal.DbManagement.Engine.Services.ExtendedKeyInfoFactory' threw an exception.
  ----> System.TypeLoadException : Method 'CreateTable' in type 'Effort.Internal.DbManagement.Engine.ExtendedTableService' from assembly 'Effort, Version=1.0.0.0, Culture=neutral, PublicKeyToken=6a46696d54971e6d' does not have an implementation.
```

No error on 2.0.4

**Comment by JonathanMagnan** [comment]
Hello @jsgoupil ,

Thank you for reporting,

I do not believe we can really fix it as the issue is in `Effort` and a new version is already available with the change required to make it work.

It's already fixed starting from v2.x in `Effort`. The package is currently in beta but in probably one or two weeks, we will release a stable version.

Let me know if that answer correctly to this issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @jsgoupil ,

The issue will be closed.

I believe we did everything we could:
- A major version of NMemory `3.0.0` has been released, it's compatible with Effort `2.x`
- NMemory version `2.0.5`, `2.0.6`, `2.0.7` are not hidden since it broke version of Effort `1.x`

Best Regards,

Jonathan

**Comment by jsgoupil** [comment]
@JonathanMagnan Thanks for coming back to me. I am quite under pressure work here so I haven't had time to try this out. I have forced no update on all my nuget for now :(

**Comment by JonathanMagnan** [comment]
Oh don't worry that's fine, thank for letting me know.

Bonne journée,

Jonathan
