### ISSUE TITLE
Query performance when there is a Foreign Key

### ISSUE THREAD

**Issue by sdg002** [zzzprojects/nmemory#36]
Hi All,
Thanks for all the efforts. Great library.

I have a question about the expected performance in a scenario involving querying on foreign keys.

**Scenario**

I have an **Employee** entity with **ID** as primary key and **Order** entity which also has **ID** as a primary key and **EmpId** as foreign key.

```
    public class Employee : EntityBase
    {
        public string FirstName { get; set; }
        public override string ToString()
        {
            return $"ID={this.ID} Name={FirstName}";
        }
    }
    public class Order : EntityBase
    {
        public int Quantity { get; set; }
        public int ItemId { get; set; }
        public int EmpId { get; set; }
        public override string ToString()
        {
            return $"ID={this.ID} Quantity={Quantity} EmpId={EmpId}  ItemId={ItemId}";
        }

    }
    public class EntityBase
    {
        private static int _id;
        public int ID{ get; set; }
        public EntityBase()
        {
            this.ID=System.Threading.Interlocked.Increment(ref _id);
        }
    }

    public class OrderManagementDb : NMemory.Database
    {
        public OrderManagementDb()
        {
            ///
            /// Create tables
            ///
            var tblEmployees= base.Tables.Create<entity.Employee, int>(p => p.ID, null);
            var tblOrders = base.Tables.Create<entity.Order, int>(p => p.ID, null);
            
            this.Employees = tblEmployees;
            this.Orders = tblOrders;
            ///
            /// Create relationship between Employee.ID and Order.EmpId
            ///
            var indexOrders_EmpId=tblOrders.CreateIndex(new NMemory.Indexes.RedBlackTreeIndexFactory(), o => o.EmpId);
            var optRelation = new NMemory.Tables.RelationOptions(false);
            this.Tables.CreateRelation(tblEmployees.PrimaryKeyIndex, indexOrders_EmpId, empid => empid, id => id,  optRelation);
        }
        public NMemory.Tables.ITable<entity.Employee> Employees { get; set; }
        public NMemory.Tables.ITable<entity.Order> Orders { get; set; }
        public NMemory.Tables.ITable<entity.OrderLineItem> OrderLineItems { get; set; }
    }

```

An Employee can have multiple Order(s).

**My experiment**

1.Populate NMEMORY database with 1000 Employee objects and 100 Order instances per Employee.
2.Fetch all employees using a simple query
2. Iterate over all the employees and query for orders for that employee . 
3. Compare the performance of querying when using NMemory database and performance when using vanilla *System.Generic.Collections.List*.

**Querying for orders of a single employee using NMemory**
```
                var allEmps = (from emp in _db.Employees select emp).ToArray();
                Trace.WriteLine($"All employees={allEmps.Count()}");
                int totalOrders = 0;
                foreach(var emp in allEmps)
                {
                    var ordersPerEmp = (from order in _db.Orders where order.EmpId == emp.ID select order).ToArray();
                    //Trace.WriteLine($"Found {ordersPerEmp.Count()} orders for employee {emp.ID}" );
                    totalOrders += ordersPerEmp.Count();
                }
                Trace.WriteLine($"Total count of all orders for all employees={totalOrders}");

```

**Querying for Orders when using regular List<>**
In this scenario, I created 2 a `List<Employee>` and `List<Order>` , got them populated and ran the following snippet.

```
                var allEmps = (from emp in _allEmployeesSimpleList select emp).ToArray();
                Trace.WriteLine($"All employees={allEmps.Count()}");
                int totalOrders = 0;
                foreach (var emp in allEmps)
                {
                    var ordersPerEmp = (from order in _allOrdersSimpleList where order.EmpId == emp.ID select order).ToArray();
                    totalOrders += ordersPerEmp.Count();
                }
                Trace.WriteLine($"Total count of all orders for all employees={totalOrders}");
```

**Populate NMEMORY database with Employee and Order objects**

```
        private static void PopulateEmployeesAndOrdersUsingNMemory(int empcount,int orderperemployee)
        {
            Trace.WriteLine($"PopulateEmployeesAndOrdersUsingNMemory");
            Stopwatch sw = new Stopwatch();
            sw.Start();
            try
            {
                for (int empindex = 0; empindex < empcount; empindex++)
                {
                    var newEmp = new entity.Employee();
                    newEmp.FirstName = $"Name ={newEmp.ID}";
                    _db.Employees.Insert(newEmp);
                    for (int orderindex = 0; orderindex < orderperemployee; orderindex++)
                    {
                        var newOrder = new entity.Order();
                        newOrder.ItemId = 0;
                        newOrder.Quantity = newOrder.ID % 10;
                        newOrder.EmpId = newEmp.ID;
                        _db.Orders.Insert(newOrder);
                    }
                }
            }
            finally
            {
                sw.Stop();
                Trace.WriteLine($"PopulateEmployeesAndOrder, time taken={sw.ElapsedMilliseconds} ms, Total employees={empcount} Order per employee={orderperemployee}");
            }
        }

```

**Observation**
I repeated the above on simple List<> and I noticed that querying on List<> outperformed NMemory by a factor of 4. I compiled using **64 bit**  and **Release** mode.   What was the design goal?

Thank you.

**Comment by sdg002** [comment]
Added some more code to demonstrate my observations

**Comment by JonathanMagnan** [comment]
Hello @sdg002 ,

Thank you for reporting, we will look at it next week and we will try to provide you an explanation.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @sdg002 ,

My developer looked at it today.

You are right, the `List` is faster because `NMemory` need to clone the entity since you cannot edit directly the entity that's stored in the memory. See: https://github.com/zzzprojects/nmemory/blob/master/Main/Source/NMemory.Shared/Execution/CommandExecutor.cs#L60-L111

So, the `retrieve` part is faster but cloning an entity take some time which makes it slower than a list since the list doesn't clone returned entity.

Let me know if that explains correctly the current behavior or you need a better explanation.

Best Regards,

Jonathan

**Comment by sdg002** [comment]
Hi @JonathanMagnan ,
Thanks for taking time to look into this. I understand why "Cloning" slows down the performance. Do you intend to provide  a switch/parameter in the future so that the client programmer can bypass the cloning ?

**Comment by JonathanMagnan** [comment]
If I understand well, you would like to skip the cloning step to change the "table data" directly?

**Comment by sdg002** [comment]
Hi @JonathanMagnan ,

In my present scenario, I am dealing with tonnes of custom POCO objects that that are processed out of documents. .I have had to write collections and Dictionaries to store and retrieve objects respectively. This becomes very very messy when the relational hierarchy becomes very deep. Not just maintaining referential integrity but querying gets penalized too. A system like NMEMORY which mimics relational database objects such as indexes and foreign keys would have greatly simplified my scenario.

I am not entirely sure that I understand the rationale behind "cloning". I was looking for a simple in memory object store that would allow me to store and retrieve objects in a relational fashion, without having to custom code using Dictionary or HashSets, etc. I think NMEMORY can become very popular.

**Comment by JonathanMagnan** [comment]
> I am not entirely sure that I understand the rationale behind "cloning

If you use an ORM like `Entity Framework` and retrieve the data, no matter how much you change the entity, changes will only be stored in the database if you call an `UPDATE` (or `SaveChanges` in EF case).

Cloning the entity in `NMemory` allow to do the same. Even if you change the entity, the change will only reflect in the `Memory` database if you call an `UPDATE`.

The Cloning make sense in this case.

---

However, I understand your request about using directly the original object since I would have used this feature when supporting `NMemory` in our library `Entity Framework Extensions` to improve the performance (instead of cloning and saving).

I will give this task to my developer, we will look at the complexity of adding an option to allow skipping the cloning if that's possible.

**Comment by JonathanMagnan** [comment]
For people looking at this issue, it's now possible to disable object cloning.

See the following issue: https://github.com/zzzprojects/nmemory/issues/50

I will close this issue since it is from 5 years ago.

---

**Are you finding this library useful? If so, please consider supporting its continued development by [becoming a sponsor](https://github.com/sponsors/zzzprojects).**

Additionally, if you think your enterprise would benefit from this library, we encourage you to suggest they [become a sponsor](https://github.com/sponsors/zzzprojects) as well. Your support will help ensure this library remains alive and well-supported.
