### ISSUE TITLE
Wrong File version in nuget of 3.1.3\lib\netstandard2.0\NMemory.dll - does not correspond to Product version

### ISSUE THREAD

**Issue by jiri-novak** [zzzprojects/nmemory#47]
There's a wrong File version of the lib\netstandard2.0\NMemory.dll in the latest (3.1.3) nuget:
![image](https://user-images.githubusercontent.com/4029967/150503076-3fbb1d38-701d-450c-b427-704fad1cd7ed.png)

For the net40/net45 version, everything is aligned and FIle version corresponds to Product version:
![image](https://user-images.githubusercontent.com/4029967/150503147-a02ffd5d-e6a3-4ff9-97c5-86f23ac8e8b1.png)

**Comment by JonathanMagnan** [comment]
Thank you for reporting,

We will look at it and release it again with the right file version.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @jiri-novak ,

Just to let you know that this one will take more time as we want to make sure we are doing the right thing. This bug currently impacts several of our packages as the file version in Visual Studio is the right one, but the one in the properties is not good. So we want to understand more about this issue first because it means that we will need to release all packages we own (which is a lot) and make sure the fix will be applied.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @jiri-novak ,

The v3.1.4 has been released. The File Version is now matching.

Best Regards,

Jon

---

**Is this library useful to you?** Please help us by [becoming a sponsor](https://github.com/sponsors/zzzprojects) to keep it alive and supported.
